services:
  web:
    build: .
    restart: unless-stopped
    container_name: web-local
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html/web:ro
    depends_on:
      - backend-core

  web-warehouse:
    build:
      context: .
      dockerfile: Dockerfile.warehouse
    restart: unless-stopped
    container_name: web-warehouse-local
    ports:
      - "8081:80"
    volumes:
      - ./pesado:/usr/share/nginx/html/pesado:ro
    depends_on:
      - backend-core

  backend-core:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    container_name: backend-core-local
    command: node --watch index.js
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SHOPIFY_SHOP_NAME=${SHOPIFY_SHOP_NAME}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
