FROM node:18-alpine

# Install postgresql-client to get pg_dump
RUN apk add --no-cache postgresql-client

WORKDIR /app

# Copy server files
COPY server/package*.json ./
RUN npm install --production

COPY server/ ./

# Command to run backup script
CMD ["node", "backup.js"]
