services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    container_name: web-prod
    volumes:
      # Mount SSL certificates (update path to your certificates)
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - VIRTUAL_HOST=${DOMAIN},www.${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN},www.${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web
    depends_on:
      - backend-core

  web-warehouse:
    build:
      context: .
      dockerfile: Dockerfile.warehouse
    ports:
      - "8081:80"
      - "8443:443"
    restart: unless-stopped
    container_name: web-warehouse-prod
    volumes:
      # Mount SSL certificates (update path to your certificates)
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - VIRTUAL_HOST=${PESADO_DOMAIN}
      - LETSENCRYPT_HOST=${PESADO_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web
    depends_on:
      - backend-core

  backend-core:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    container_name: backend-core-prod
    environment:
      - PORT=3000
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SHOPIFY_SHOP_NAME=${SHOPIFY_SHOP_NAME}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
    networks:
      - web

networks:
  web:
    driver: bridge
